### PR TITLE
Speed up parsing IPv6 addresses

### PR DESCRIPTION
**Pull request by bdraco**
- Only do the int conversion once in `ipv6_prefixlength` since the underlying `ipaddress` module will do it every time

int_every_time

- Avoid trying to construct ipv4 addresses when we know its an ipv6 address in `sockaddr_to_ip` since `ip_address` tries ipv4 first, fails, and than tries ipv6

https://github.com/python/cpython/blob/974847be443e9798615e197ec6642e546a71a6b0/Lib/ipaddress.py#L46

On my system which has 28 ipv6 addresses running Python 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin

before
```
# python3 bench/ifaddr.py
Calling get_adapters 10000 took 6.78751229098998 seconds
```
after
```
# python3 bench/ifaddr.py
Calling get_adapters 10000 took 3.899116750084795 seconds
```

```python
from ifaddr import get_adapters
import time
iterations = 10000
start = time.perf_counter()
for _ in range(iterations):
    get_adapters()
duration = time.perf_counter() - start
print(f"Calling get_adapters {iterations} took {duration} seconds")
```

--
single function
--

```
original: 1.1566431249957532
new: 0.5491334999678656
```

script

```python
import ipaddress
import timeit


def ipv6_prefixlength_new(address: ipaddress.IPv6Address) -> int:
    prefix_length = 0
    address_as_int = int(address)
    for i in range(address.max_prefixlen):
        if address_as_int >> i & 1:
            prefix_length = prefix_length + 1
    return prefix_length


def ipv6_prefixlength_original(address: ipaddress.IPv6Address) -> int:
    prefix_length = 0
    for i in range(address.max_prefixlen):
        if int(address) >> i & 1:
            prefix_length = prefix_length + 1
    return prefix_length


test_addr = ipaddress.IPv6Address('ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff')

original = timeit.timeit(lambda: ipv6_prefixlength_original(test_addr), number=100000)
new = timeit.timeit(lambda: ipv6_prefixlength_new(test_addr), number=100000)
print(f'original: {original}')
print(f'new: {new}')
```

### CODE REVIEW

**Comment by jstasiak** [comment]
Hey @bdraco, thanks for the patch. Can you please provide some benchmark details in the PR description (benchmark code, before/after numbers, Python version etc.)?

**Comment by bdraco** [comment]
I'll post my benchmark code as soon as I get back home

**Comment by bdraco** [comment]
Benchmark and script added to the opening text

**Comment by jstasiak** [comment]
Thank you. I understand that *this* code will be faster (but no numbers for `sockaddr_to_ip`?).

My question wasn't clear, let me clarify: do you have a benchmark or a scenario using this module's public API that shows a measurable speed improvement? I'd like performance changes to be accompanied by information about how they improve things for the module's users.

**Comment by bdraco** [comment]
> Thank you. I understand that _this_ code will be faster (but no numbers for `sockaddr_to_ip`?).

The change for `sockaddr_to_ip` de minimis so I don't include it.

> 
> My question wasn't clear, let me clarify: do you have a benchmark or a scenario using this module's public API that shows a measurable speed improvement? I'd like performance changes to be accompanied by information about how they improve things for the module's users.

```python
from ifaddr import get_adapters
import time
iterations = 10000
start = time.perf_counter()
for _ in range(iterations):
    get_adapters()
duration = time.perf_counter() - start
print(f"Calling get_adapters {iterations} took {duration} seconds")
```

On my system which has 28 ipv6 addresses running Python 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
https://github.com/python-zeroconf/python-zeroconf/blob/master/bench/create_destory.py

before
```
# python3 bench/ifaddr.py
Calling get_adapters 10000 took 6.78751229098998 seconds
```
after
```
# python3 bench/ifaddr.py
Calling get_adapters 10000 took 3.899116750084795 seconds
```

**Comment by bdraco** [comment]
I also expect the number of ipv6 addresses I have have is major factor here so I'm not sure how much difference it will make unless someone is starting and stopping like `zeroconf` often or something else that uses this module on a server with lots of virtual host, tunnels, etc.

**Comment by bdraco** [comment]
I did a bit more testing on Linux

With IPv6 disabled: no effective change in timing

With lots of IPv6 addresses the speed up increases.

**Comment by jstasiak** [comment]
Thank you, I think that's great to have. I'll merge this once I've fixed the CI pipeline.

Do you need this to be released shortly or can it wait?

**Comment by bdraco** [comment]
Thanks. No rush. I managed to workaround the issue for the user who original reported the issue downstream, but figured it would help others.

**Comment by bdraco** [comment]
thanks

**Comment by jstasiak** [comment]
Oh no – thank *you*

**Pull request merged**
